language: node_js
node_js:
  - 14
install:
  - npm i
cache: npm
jobs:
  include:
    - stage: lint
      script: npm run linter
    - stage: test
      script: npm run test
deploy:
  provider: heroku
  api_key: bab2414b-cf9a-4358-81b4-0e81a45c3dd4
  on:
    condition: all_branches